"""Locate the workflow journals that the synthetic-data generation rounds wrote.

The instruct corpus was generated by fanning out agent workflows, each of which
appends its results to a `journal.jsonl` under the agent runtime's own project
directory. The harvest scripts in this folder read those journals and turn them
into the JSONL corpora under data/synthetic/.

That directory lives outside this repository and its location is machine
specific, so it is resolved at runtime rather than hardcoded:

  1. $SPROCKET_JOURNAL_ROOT, if set. Point this at the project directory that
     contains the session folders.
  2. Otherwise the first match for ~/.claude/projects/*LLM*.

These scripts are only needed to regenerate the synthetic corpus, which is not
distributed with this repository. Pretraining does not use them.
"""
from __future__ import annotations

import glob
import os


def project_root() -> str:
    """Return the directory holding the agent session folders.

    Raises SystemExit with an actionable message rather than failing later with
    a confusing FileNotFoundError on a path nobody recognises.
    """
    env = os.environ.get("SPROCKET_JOURNAL_ROOT")
    if env:
        if not os.path.isdir(env):
            raise SystemExit(
                f"SPROCKET_JOURNAL_ROOT is set to {env!r}, which is not a directory.")
        return env

    guesses = sorted(glob.glob(os.path.join(
        os.path.expanduser("~"), ".claude", "projects", "*LLM*")))
    if guesses:
        return guesses[0]

    raise SystemExit(
        "Could not locate the workflow journals.\n"
        "Set SPROCKET_JOURNAL_ROOT to the agent project directory containing the\n"
        "session folders, e.g.\n"
        "  set SPROCKET_JOURNAL_ROOT=%USERPROFILE%\\.claude\\projects\\<project-dir>\n"
        "These scripts regenerate the synthetic corpus, which is not distributed\n"
        "with this repository. See the README.")


def journal(session: str, run_id: str) -> str:
    """Path to one run's journal.jsonl, given its session folder and run id."""
    return os.path.join(project_root(), session, "subagents", "workflows",
                        run_id, "journal.jsonl")
